language: python

python:
 - pypy
 - pypy3
 - 2.6
 - 2.7
 - 3.2
 - 3.3
 - 3.4
 - 3.5

install:
 - pip install pyflakes
 - sudo apt-get update
 - sudo apt-get install rtmpdump python python-crypto php5-cli php5-curl php5-mcrypt
 - sudo php5enmod mcrypt

script:
 - pyflakes yle-dl
 - sudo make install
 - yle-dl --help

after_script:
 - pip install pep8
 - pep8 --statistics --count yle-dl

matrix:
  fast_finish: true
  allow_failures:
    - python: 3.2
