language: python

python:
 - pypy
 - pypy3
 - 2.7
 - 2.6
 - 3.6
 - 3.5
 - 3.4
 - 3.3

sudo: true

install:
 - pip install pyflakes
 - sudo apt-get install rtmpdump python python-crypto php5-cli php5-curl php5-mcrypt
 - sudo php5enmod mcrypt
 - sudo make install

script:
 - pyflakes yle-dl
 - yle-dl --help

after_script:
 - pip install pep8
 - pep8 --statistics --count yle-dl

matrix:
  allow_failures:
  - python: pypy3
  - python: 3.6
  - python: 3.5
  - python: 3.4
  - python: 3.3
